import type { Metadata } from "next";
import {Figtree} from "next/font/google"
import "./globals.css";
import Head from "next/head";

const figtree = Figtree({subsets:['latin'], weight:[ "500", "800"]})

export const metadata: Metadata = {
  title: "blog preview card",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={figtree.className}>{children}</body>
    </html>
  );
}
